### ISSUE TITLE
Defacing templates not found on the /neurospin/local install

### ISSUE THREAD

**Issue by ylep** [neurospin/neurospin_to_bids#9]
```
Traceback (most recent call last):
  File "/neurospin/local/neurospin_to_bids/venv/bin/neurospin_to_bids", line 11, in <module>
    load_entry_point('neurospin-to-bids==0.0.0', 'console_scripts', 'neurospin_to_bids')()
  File "/neurospin/local/neurospin_to_bids/venv/lib/python3.6/site-packages/neurospin_to_bids/__main__.py", line 913, in main
    dry_run=args.dry_run[0])
  File "/neurospin/local/neurospin_to_bids/venv/lib/python3.6/site-packages/neurospin_to_bids/__main__.py", line 820, in bids_acquisition_download
    force=True)
  File "/neurospin/local/neurospin_to_bids/venv/lib/python3.6/site-packages/pydeface/utils.py", line 86, in deface_image
    template, facemask = initial_checks(template, facemask)
  File "/neurospin/local/neurospin_to_bids/venv/lib/python3.6/site-packages/pydeface/utils.py", line 23, in initial_checks
    raise Exception('Missing template: %s' % template)
Exception: Missing template: /neurospin/local/neurospin_to_bids/venv/lib/python3.6/site-packages/template_deface/mean_reg2mean.nii.gz
```

**Comment by DimitriPapadopoulos** [comment]
Have I missed something while installing?

**Comment by isadenghien** [comment]
Hi, yes the  template_deface  directory is missing (with template including part of face and ears for defacing).
I'm going to add it.
